# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a184cdb54c059a112009988fec35632a041e78609dda5ccdd62fee5a73f739c87262134f21cfd73a7784a566e168724d7d94b9ed61e5e72e52226dfcd165e7d1

test:
  secret_key_base: 00c734c2df8115a16a34e2f4176a228d47e832404f84b8111e769c09aa98f3542279b7b44bc61a5ad31893c9ab654fc0dd2585a621bfee207b8f435c3374e57a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
